### ISSUE TITLE
Mock Builder VM

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/mock_builder#2]
Is it worth it at this point in Slate's life cycle to make Mock Builder run in a VM?

**Comment by adamjohnson** [comment]
If it's quick and you're familiar with the process, then I'd say yes. Otherwise whenever there's a new designer in the colleges we'll have to install RVM and all things `mock_builder` then install `hammer-vm` too. Many folks still have 80%+ of their sites in Slate, :disappointed:.

Might as well keep them congruent, eh?

**Comment by zeroedin** [comment]
Yeah I guess that's true.   I should be able to fire it out the same way.

**Comment by zeroedin** [comment]
It's alive..... [Mock-Builder-VM](https://github.com/wvuweb/mock-builder-vm)
